version: '3'

networks:
  app_minio:
    name: app_minio
    driver: bridge

volumes:
  minio_data:
  db_data_minio:

services:
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio99
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
        - app_minio

  mysql_minio:
      image: mysql:latest
      container_name: mysql_minio
      restart: unless-stopped
      tty: true
      ports:
          - "3306"
      deploy:
          resources:
              limits:
                  cpus: '2'
                  memory: 4096M
              reservations:
                  cpus: '1'
                  memory: 512M
      volumes:
          - db_data_minio:/var/lib/mysql
      environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          SERVICE_TAGS: dev
          SERVICE_NAME: ${DB_CONNECTION}
      networks:
          - app_minio

  app_minio:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app_minio
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.50'
          memory: 128M
    depends_on:
      - minio
      - mysql_minio
    external_links:
      - minio
      - mysql_minio
    networks:
      - app_minio
